### ISSUE TITLE
Matriz de periodização o curso

### ISSUE THREAD

**Issue by jairofsouza** [jairofsouza/EstimarOfertaVagas-Web#10]
Criar uma matriz que mostra qual o período que o aluno está e em qual ele deveria estar. Por exemplo:

     1     2     3    4     5
     1     40    0    0     0 
     2     10    30   0     0     
     3     5     20   15    0     
     4     ...
     5     ...

A matriz acima mostra que 40 alunos deveriam estar no primeiro período e realmente estão no primeiro período (celula 1x1). 30 alunos deveriam estar no segundo período (celula 2x2) mas 10 ainda estão no primeiro (celula 2x1).

**Comment by jairofsouza** [comment]
Colocar no final a soma de cada coluna.

**Comment by jairofsouza** [comment]
@leonardoab não fechei essa issue pq não me lembro de ver essa soma na matriz. Você chegou a fazer?

**Comment by leonardoab** [comment]
Boa noite Jairo,
Sim esta feita por turma o total geral
