### ISSUE TITLE
Gráfico de reprovações em disciplinas

### ISSUE THREAD

**Issue by jairofsouza** [jairofsouza/EstimarOfertaVagas-Web#13]
Contabilizar quantas reprovações acontecem em cada disciplina. Permitir escolher reprovações por RI ou por nota ou ambas.

**Comment by leonardoab** [comment]
Seria um percentual né?Pois pode existir disciplinas que foram cursadas menos que outras.Certo?
Percentual = numero reprovação / numero de aprovação + numero de reprovação

No número de reprovação poderia existir um filtro (RI ou Nota)

**Comment by jairofsouza** [comment]
Nao precisaria ser percentual. A ideia é mesmo ver por disciplina, mas o foco seria nas obrigatórias (embora nao precise dessa restrição). A ideia seria mostrar: Algoritmos: X, ED: Y. X = numero de tentativas de insucesso de alunos do curso (RN ou RI). Contudo, pensando aqui, nao ter uma referencia pode ser ruim. Entao podemos pensar nesse gráfico como 2 (ou tudo num mesmo ou 2 gráficos ou 1 com opções):

1) Um grafico do tipo: disciplina: X / Y ( que quer dizer que X tentativas frustradas houveram na disciplina e foram Y alunos envolvidos. Ou seja, Y tiveram ao menos 1 reprovação, mas X é o total de reprovações)

2) Um grafico do tipo: disciplina: % reprovações que quer dizer, de todos os alunos do curso, quantos já se reprovaram na disciplina. Pegaria X dividido por Y, onde X é o numero de alunos que tiveram alguma reprovação na disciplina e Y o numero de alunos que já tiveram alguma matriucla na disciplina.
