### ISSUE TITLE
Quantas horas um discente leva para formar

### ISSUE THREAD

**Issue by jairofsouza** [jairofsouza/EstimarOfertaVagas-Web#14]
Quantas horas contando suas reprovações? Considere que um aluno em monografia é formando. 
Atualmente seria a unica forma de calcular, visto que só temos alunos ativos. Vale a pena ou pode distorcer demais os dados?

**Comment by leonardoab** [comment]
Acho que é muito arriscado fazer essa expectativa, pois dependendo dos alunos desperiodizados pode distorcer bastante os dados.
Podemos fazer uma expectativa a partir do desempenho até aquele momento, ou considerando o desempenho dos alunos dos últimos 4 períodos.
Exemplo Joao tem um percentual de aprovação de 80%: carga horaria total até o momento + carga horaria que falta + 20% = numero de horas médias de curso.

**Comment by jairofsouza** [comment]
Essa issue vamos deixar para uma segunda versao do sistema, quando tivermos dados histórico (um outro projeto futuro).

**Comment by rodrigoluis** [comment]
Alô @jairofsouza. Em conversa com o Heder achamos que essa funcionalidade não será muito útil para o nosso contexto atual. Quer manter essa issue ou pode fechar (no caso, você mesmo fechar)?

**Comment by jairofsouza** [comment]
@rodrigoluis todas as issues que dependem de uma reestruturação do sistema ou que não são interessante para agora, eu coloquei com label "Versao 2.0". Sugiro fazer o mesmo pra outras que vcs identificarem. Essa issue, por exemplo, só dá pra resolver se guardarmos dados históricos (não remover dados antigos) do sistema e isso demanda uma reestrutura grande no sistema.
