### ISSUE TITLE
Gráfico de alunos x IRA

### ISSUE THREAD

**Issue by jairofsouza** [jairofsouza/EstimarOfertaVagas-Web#15]
Fazer um gráfico com o IRA de cada aluno (eixo Y) e a turma do aluno (eixo X). Permitir que possa dar zoom no gráfico

**Comment by leonardoab** [comment]
Teríamos que pensar melhor nesse gráfico pois como a variação de ira é grande pode existir grandes acúmulos em alguns pontos com isso será inviável realizar um zoom para um ponto.
Um opção seria a seleção do intervalo de IRA ex : 60 - 70

**Comment by jairofsouza** [comment]
O efeito será parecido com o gráfico panoramico que o Joao Victor estava fazendo. E ele fez o zoom que ficou bom. Acho que nao teremos problema, mas vamos testar primeiro.
