### ISSUE TITLE
Reproduzir gráfico panoramico do curso

### ISSUE THREAD

**Issue by jairofsouza** [jairofsouza/EstimarOfertaVagas-Web#3]
Criar um gráfico igual ao abaixo
![captura de tela 2015-09-06 as 14 28 12](https://cloud.githubusercontent.com/assets/3019521/9722354/097b6b42-5582-11e5-810b-f151c41abc28.png)

Neste gráfico temos no eixo x a quantidade de horas que o aluno completou do curso e no eixo y qual o período que o aluno se encontra (quantos cursou). Cada bola representa um aluno do curso. O tamanho da bola representa quantos créditos o aluno precisa fazer ainda por período para formar dividido pelo numero de períodos que ele ainda pode ter (tempo máximo de curso). Fazer com que as bolas vão da cor verde para vermelho. Quanto maior a bola, mais vermelho. Quando menor, mais verde.

Essa linha reta significa a linha de tendência do gráfico

Colocar também uma linha de "curso ideal" do aluno.

**Comment by leonardoab** [comment]
Boa noite Jairo,
Veja se é isso que vc descreveu:
Cada aluno vai ter um circulo que vai esta posicionado no eixo (X) pela quantidade de horas concluídas e em (Y) qual período ele se encontra, se o aluno estiver atrasado o circulo vai estar maior se ele estiver periodizado / adiantado vai ficando menor.
É isso?

**Comment by jairofsouza** [comment]
Está correto. O eixo Z (leia-se: raio do circulo) é dependente da quantidade de horas que o aluno precisa fazer por periodo para conseguir formar no prazo máximo do curso (horas que faltam / periodos que faltam)
