### ISSUE TITLE
Problemas com ACEs sem dono

### ISSUE THREAD

**Issue by jairofsouza** [jairofsouza/EstimarOfertaVagas-Web#38]
Enquanto eu tava olhando a tabela de ACEs do banco, reparei que tinha muitas ACEs cadastradas mas que não tinha nenhum aluno associado (aluno = null). Pelo que vi, parece que semrpe que for realizada uma importação de dados, as ACEs daquele curso vão sumir, porque todos os alunos são deletados, o que faz perder a referencia da ACE.

**Comment by jairofsouza** [comment]
@SouzaJBR, lembro que discutimos isso. Favor colocar a explicação aqui para ficar registrado.

**Comment by SouzaJBR** [comment]
Esse problema ocorre pois a importação precisa remover todos os alunos do curso antes de colocar os novos. Para contornar isso e evitar que as ACEs ficassem sem dono, adicionei um campo de matrícula nas ACEs e algumas operações de listar as ACEs do aluno usam esse campo. Assim, mesmo se o aluno for retirado e adicionado novamente, o sistema irá possuir uma referência de quem é o dono daquela ACE.
