### ISSUE TITLE
Erro no calculo de IRA

### ISSUE THREAD

**Issue by jairofsouza** [jairofsouza/EstimarOfertaVagas-Web#40]
Há um erro muito grande no calculo de IRAs no sistema. Ver problema do aluno 201035053. Os IRAs calculados deveriam ser bem mais altos, principalmente para os períodos 2015.3 e 2016.1. Possiveis causas: as disciplinas que estão com SC não contam no IRA (nem no denominador nem na soma!). Ainda assim, mesmo se eu considerasse, o IRA que eu calculei foi bem maior que o que está no sistema. Nao sei o que está havendo. Acabei de atualizar os históricos para conseguir verificar.

**Comment by jairofsouza** [comment]
O siga agora está disponibilizando um gráfico igual ao do sistema nosso. Mas olha que diferença o gráfico que ele está gerando pra esse aluno e o que estamos gerando (note também o primeiro ponto do grafico, como se difere).

![captura de tela 2017-01-23 as 09 33 22](https://cloud.githubusercontent.com/assets/3019521/22202418/38e2f7ec-e14f-11e6-9783-a68a23bf93ef.png)
![captura de tela 2017-01-23 as 09 33 05](https://cloud.githubusercontent.com/assets/3019521/22202419/38e8cb4a-e14f-11e6-967d-94a0cbee1985.png)

**Comment by jairofsouza** [comment]
O gráfico acima mostra o IRA acumulado (linha amarela nossa).

**Comment by jairofsouza** [comment]
@SouzaJBR cadê o commit pra essa issue?

**Comment by jairofsouza** [comment]
@SouzaJBR pode dar uma olhada de novo no caso desse aluno? Veja o seguinte: no gráfico do SIGA, o primeiro IRA dele acumulado é de quase 80. No nosso sistema é de 74.68. O do segundo periodo acumulado é de pouco acima de 60 no caso do SIGA. No nosso é de 58.99. Ou seja, tem um erro aí nesse calculo ainda (nosso ou do SIGA). Pode fazer as contas na mão e ver o que tá errado?

**Comment by SouzaJBR** [comment]
No commit 3aaa3c8e41022cc53cf71129111224a7033a0d18, a parte de cálculo do IRA foi refeita. Agora ele está sendo gerado diretamente pelo sistema na hora da importação dos dados e fica persistido no banco de dados, agilizando o sistema e fazendo o cálculo ser mais preciso.

Nesse caso, o gráfico gerado pelo sistema (linha amarela) correspondeu ao gráfico gerado pelo SIGA.
![captura de tela de 2017-05-04 16 44 37](https://cloud.githubusercontent.com/assets/5217594/25722224/bfd6ba38-30e9-11e7-8917-89224d92883e.png)
