### ISSUE TITLE
Aluno não aparece no sistema

### ISSUE THREAD

**Issue by jairofsouza** [jairofsouza/EstimarOfertaVagas-Web#41]
Aluno 201535043 não está aparecendo no sistema.

**Comment by jairofsouza** [comment]
Enviei mensagem ao Daves para tentar resolver.

**Comment by jairofsouza** [comment]
Agora apareceu. Não dá pra saber o que houve. Esperar pra ver se o erro se repete período que vem.

**Comment by rodrigoluis** [comment]
Alô @jairofsouza. Quando puder, feche essa issue. Se o problema reaparecer abriremos uma nova.
