### ISSUE TITLE
Disciplinas opcionais aparecem como 4h ao invés de 60h

### ISSUE THREAD

**Issue by jairofsouza** [jairofsouza/EstimarOfertaVagas-Web#44]
Tela de situação do aluno está calculando errado a quantidade de horas.

![captura de tela 2017-02-24 01 07 47](https://cloud.githubusercontent.com/assets/3019521/23301472/d5ab7a4a-fa68-11e6-87e0-28a7e6725da0.png)

**Comment by jairofsouza** [comment]
Mesmo no sistema antigo, ainda tem problemas com opconais. Quando vc voltou a versão, aqueles essas disciplinas opcionais começaram a contar 60h corretamente. Mas encontrei um caso de um aluno (201235020) que fez uma disciplina do mestrado e tá contando 3h (mas são 3creditos, ou seja, 45h). No histórico dele está correto... dá uma olhada nesse caso também, por favor. Erro na importação?!

**Comment by SouzaJBR** [comment]
Consegui identificar e corrigir o problema. O problema é que as disciplinas opcionais não possuem informação na árvore em que os dados são puxados.  Logo, era utilizado o valor padrão de 4h para a disciplina. No commit 6fa7cba7cd149e0db7e7f95597244bb9fbe27a3a, foi corrigido tanto a exibição no grid, quanto o cálculo de horas (que usava a informação errada).
