### ISSUE TITLE
Evolução da turma no gráfico #3

### ISSUE THREAD

**Issue by jairofsouza** [jairofsouza/EstimarOfertaVagas-Web#5]
Permitir que no gráfico #3 possa se verificar a evolução de uma turma em 2 períodos.
   Por exemplo, filtrar uma certa turma 2010 (#4). Depois disso, verificar como essa turma estava em 2011.3 e em 2012.1. Colocaria cada um de uma cor. Assim é possível ver se a turma caminhou ou nao.

**Comment by rodrigoluis** [comment]
Alô @jairofsouza. Não entendemos exatamente o que você queria ver com essa funcionalidade. Poderia dar uma clareada?

**Comment by jairofsouza** [comment]
@rodrigoluis a ideia é entender como uma turma evoluiu de um semestre pro outro: quem ficou estagnado em numero de horas, quem evoluiu mais (completou mais horas), etc. Qual gráfico usar (e qual a prioridade de implementação) ainda precisa ser discutido melhor.
