### ISSUE TITLE
Trocar esse Qtd Horas Período por Horas de ACE

### ISSUE THREAD

**Issue by Lcdcampos** [jairofsouza/EstimarOfertaVagas-Web#55]
Em http://200.131.219.214:8080/SistemaGestaoCurso/PlanejamentoFormatura.xhtml
Trocar esse Qtd Horas Período por Horas de ACE e fazer a relação igual nas demais: Horas Realizadas / Horas Obrigatórias.

Porque está fixo em 360 para qualquer aluno. 360 horas é o obrigatório e para SI - para CC é 300 horas.
E além disso, para manter padrão comas demais, traz o que já foi concluído / total de horas obrigatório.

**Comment by jairofsouza** [comment]
Vc está confundindo. Esse qtd de horas não é ACE. É quantas horas de aula o
aluno vai fazer por periodo. Por isso está editável.

Abs,
Jairo

2018-04-25 23:04 GMT-03:00 Lcdcampos <notifications@github.com>:

**Comment by Lcdcampos** [comment]
Confundi não, eu não tinha entendido isso.
Beleza, vou apagar essa issue.
Att.,
Luciana.

Em 25 de abril de 2018 23:18, jairofsouza <notifications@github.com>
escreveu:
