### ISSUE TITLE
Gráfico de periodização

### ISSUE THREAD

**Issue by jairofsouza** [jairofsouza/EstimarOfertaVagas-Web#8]
Criar um gráfico de barra mostrando, para cada turma, quantos alunos estão em cada período do curso?
   Por exemplo, criar uma barra para a turma 2010. Nela, colocar vários pedaços: quantos alunos estão no segundo período (fecharam todas as disciplinas do primeiro), quantos estão no terceiro, etc. O tamanho da barra é igual à quantidade total de alunos na turma.

   Permitir também que se agrupe todas as turmas (ou seja, quantos alunos no total do curso fecharam o 3o período, etc?)

**Comment by leonardoab** [comment]
Boa noite Jairo,
Neste gráfico sera computado as horas de opcionais e eletivas?
Por exemplo se ele completou todas obrigatórias do período mas não tem horas suficiente para completar as eletivas/opcionais?Ele estará estará em que período?
Somente iremos considerar as obrigatórias?
Att.

**Comment by jairofsouza** [comment]
Pode considerar somente as obrigatórias. Contudo, coloque no título do gráfico (ou em outro local da tela) informando que está considerando somente disciplinas obrigatórias.

**Comment by jairofsouza** [comment]
@leonardoab conferir se tem esse aviso que está sendo usando comente disciplinas obrigatórias, por favor.
